version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: convert_tool_video
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  api:
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg2://root:password@database:5432/convert_tool_video
    build:
      context: ./api
    networks:
      - mynetwork