version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg2://root:password@database:5432/convert_tool_video

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: convert_tool_video
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
