version: '3'

networks:
  mynetwork:
    driver: bridge

services:

  redis:
    image: redis:latest
    container_name: mi-redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: convert_tool_video
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  celery:
    container_name: celery
    volumes:
      - files:/uploads/videos
    command: celery -A workers.celery worker --loglevel=info -B
    build:
      context: ./celery
    depends_on:
      - redis
    networks:
      - mynetwork

  api:
    container_name: api
    volumes:
      - files:/uploads/videos
    ports:
      - "5000:5000"
    depends_on:
      - database
      - celery
      - redis
    build:
      context: ./api
    networks:
      - mynetwork

volumes:
  files: